version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: local_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t
      MYSQL_DATABASE: remit
    volumes:
      - ./db/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
