spring:
  datasource:
    url: jdbc:mysql://localhost:3306/remit
    username: root
    password: 1q2w3e4r5t
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  config:
    activate:
      on-profile: local